site_name: Codesmine


theme: readthedocs

nav:
    - '智能家居套裝':
        - 簡介: smarthome/1.md
        - smarthome/2.md
        - smarthome/3.md
        - smarthome/4.md
        - smarthome/5.md
        - smarthome/6.md
        - smarthome/7.md
        - smarthome/8.md

