site_name: Codesmine


theme: readthedocs

nav:
    - 智能家居:
        - smarthome/index.md:
        - 第一課: smarthome/1.md


    - '智慧城市物聯網課程':
        - smartcity/intro.md
        - smartcity/1.md
        - smartcity/2.md
        - smartcity/3.md
        - smartcity/4.md
        - smartcity/5.md
        - smartcity/6.md
        - smartcity/7.md
        - smartcity/8.md
        - smartcity/9.md
        - smartcity/10.md


extra:
  generator: false
