extra:
  generator: false

site_name: Codesmine

theme: readthedocs
logo: logo.png

nav:
    - '智能家居套裝課程':
        - smarthome/1.md
        - smarthome/2.md
        - smarthome/3.md
        - smarthome/4.md
        - smarthome/5.md
        - smarthome/6.md
        - smarthome/7.md
        - smarthome/8.md

    - '智慧城市物聯網課程':
        - smartcity/intro.md
        - smartcity/1.md
        - smartcity/2.md
        - smartcity/3.md
        - smartcity/4.md
        - smartcity/5.md
        - smartcity/6.md
        - smartcity/7.md
        - smartcity/8.md
        - smartcity/9.md
        - smartcity/10.md


